server:
  port: 8080
springdoc:
  swagger-ui:
    operations-sorter: "method"
    path: /v1/swagger-ui
    url: /v1/api-docs
  api-docs:
    path: /v1/api-docs
spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/board
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
token:
  refresh-secret-key: ${REFERESH_SECRET_KEY}
  secret-key: ${SECRET_KEY}
  token-time: 900 # AccessToken: 900초(15분), 15분마다 갱신 필요, AccessToken은 짧은 유효기간
  refresh-token-time: 604800 # RefreshToken: 604800초(7일), 7일 동안 유효, RefreshToken은 긴 유효기간
logging:
  file:
    name: /var/logs/kobe-bulletin-board/application.log # 로그파일경로
  level:
    com.devkobe24.kobe_bulletin_board.security: DEBUG
    com.devkobe24.kobe_bulletin_board.domain.auth: INFO
    root: WARN
