server:
  port: 8080
springdoc:
  swagger-ui:
    operations-sorter: "method"
  api-docs:
    enabled: true
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/board"
    username: "root"
    password: "SkyAchieve910424"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
token:
  refresh-secret-key: "REFRESH_SECRET"
  secret-key: "SECRET"
  token-time: 300
  refresh-token-time: 300