server:
  port: 8080
springdoc:
  swagger-ui:
    operations-sorter: "method"
    path: /v1/swagger-ui
  api-docs:
    path: /v1/api-docs
spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        cache:
          use_second_level_cache: false
          use_query_cache: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/board
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
token:
  refresh-secret-key: ${REFERESH_SECRET_KEY}
  secret-key: ${SECRET_KEY}
  token-time: 300
  refresh-token-time: 300
logging:
  file:
    name: /var/logs/kobe-bulletin-board/application.log # 로그파일경로
  level:
    com.devkobe24.kobe_bulletin_board.security.JWTProvider: DEBUG
    root: INFO #로그레벨