package com.devkobe24.kobe_bulletin_board.common.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ResponseCode implements CodeInterface {
	SUCCESS(0, "SUCCESS"),

	USER_ALREADY_EXISTS(-1,"USER_ALREADY_EXIST"),
	USER_SAVED_FAILED(-2, "USER_SAVED_FAILED"),
	USER_NOT_EXISTS(-3,"USER_NOT_EXISTS"),

	MISS_MATCH_PASSWORD(-4,"MISS_MATCH_PASSWORD"),

	ACCESS_TOKEN_IS_NOT_EXPIRED(-5,"ACCESS_TOKEN_IS_NOT_EXPIRED"),
	TOKEN_IS_INVALID(-6,"TOKEN_IS_INVALID"),
	TOKEN_IS_EXPIRED(-7,"TOKEN_IS_EXPIRED"),

	POST_SAVED_FAILED(-8,"POST_SAVED_FAILED"),
	NICK_NAME_ALREADY_EXISTS(-9,"NICK_NAME_ALREADY_EXISTS"),
	POST_NOT_EXISTS(-10,"POST_NOT_EXISTS"),
	POST_READ_FAILED(-11,"POST_READ_FAILED"),
	TOKEN_IS_NOT_EXISTS(-12,"TOKEN_IS_NOT_EXISTS"),
	USER_EMAIL_EXISTS(-13,"USER_EMAIL_EXISTS"),
	USER_ALREADY_LOGIN(-14,"USER_ALREADY_LOGIN"),
	POST_NOT_FOUND(-15, "POST_NOT_FOUND"),
	MODIFY_SAME_PASSWORD(-16,"MODIFY_SAME_PASSWORD"),
	MODIFY_SAME_TITLE(-17,"MODIFY_SAME_TITLE"),
	MODIFY_SAME_CONTENT(-18,"MODIFY_SAME_CONTENT"),
	UNEXPECTED_ERROR(-19,"UNEXPECTED_ERROR"),
	USER_READ_FAILED(-20,"USER_READ_FAILED"),
	USER_LIST_EMPTY(-21,"USER_LIST_EMPTY");



	private final Integer code;
	private final String message;
}
